# This is the BeamMP-Server config file.
# Help & Documentation: `https://wiki.beammp.com/en/home/server-maintenance`
# IMPORTANT: Fill in the AuthKey with the key you got from `https://beammp.com/k/dashboard` on the left under "Keys"

[General]
Name = "bepis big gaming"
Port = 30814
# AuthKey has to be filled out in order to run the server
AuthKey = "test"
# Whether to log chat messages in the console / log
LogChat = true
Debug = false
Private = true
MaxCars = 20
MaxPlayers = 800000
Map = "/levels/west_coast_usa/info.json"
Description = "BeamMP Default Description"
ResourceFolder = "Resources"

[Misc]
# Hides the periodic update message which notifies you of a new server version. You should really keep this on and always update as soon as possible. For more information visit https://wiki.beammp.com/en/home/server-maintenance#updating-the-server. An update message will always appear at startup regardless.
ImScaredOfUpdates = false
# If SendErrors is `true`, the server will send helpful info about crashes and other issues back to the BeamMP developers. This info may include your config, who is on your server at the time of the error, and similar general information. This kind of data is vital in helping us diagnose and fix issues faster. This has no impact on server performance. You can opt-out of this system by setting this to `false`
SendErrorsShowMessage = true
# You can turn on/off the SendErrors message you get on startup here
SendErrors = true

[HTTP]
# Which IP to listen on. Pick 0.0.0.0 for a public-facing server with no specific IP, and 127.0.0.1 or 'localhost' for a local server.
HTTPServerIP = "127.0.0.1"
SSLKeyPath = "./.ssl/HttpServer/key.pem"
SSLCertPath = "./.ssl/HttpServer/cert.pem"
HTTPServerPort = 8080
# Recommended to have enabled for servers which face the internet. With SSL the server will serve https and requires valid key and cert files
UseSSL = false
# Enables the internal HTTP server
HTTPServerEnabled = false
