name: CMake Linux Build

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Install Dependencies
        run: sudo ./scripts/debian/1-install-deps.sh

      - name: Create Build Environment
        working-directory: ${{github.workspace}}/build-linux
        run: ./scripts/debian/2-configure.sh

      - name: Build Server
        working-directory: ${{github.workspace}}/build-linux
        run: ./scripts/debian/3-build.sh

      - name: Build Tests
        working-directory: ${{github.workspace}}/build-linux
        run: ./scripts/debian/3-build-tests.sh

      - name: Archive server artifact
        uses: actions/upload-artifact@v2
        with:
          name: BeamMP-Server-linux
          path: ${{github.workspace}}/build-linux/BeamMP-Server

      - name: Archive test artifact
        uses: actions/upload-artifact@v2
        with:
          name: BeamMP-Server-linux-tests
          path: ${{github.workspace}}/build-linux/BeamMP-Server-tests

  run-tests:
    needs: linux-build
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/download-artifact@master
        with:
          name: BeamMP-Server-linux-tests
          path: ${{github.workspace}}
    
      - name: Install Runtime Dependencies
        run: sudo ./scripts/debian/4-install-runtime-deps.sh

      - name: Test
        working-directory: ${{github.workspace}}
        shell: bash
        run: |
            chmod +x ./BeamMP-Server-tests
            ./BeamMP-Server-tests
