name: Debian 11 Build

on: [push]

jobs:
  debian-11-build:
    runs-on: ubuntu-latest
    container:
      image: debian:11
    steps:
      - name: Install git
        run: |
          apt-get update -y
          apt-get install -y git

      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Git config safe directory
        shell: bash
        run: bash ./scripts/debian/1.5-git-safe.sh

      - name: Install Dependencies
        run: bash ./scripts/debian/1-install-deps.sh

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Create Build Environment
        run: bash ./scripts/debian/2-configure.sh

      - name: Build Server
        run: bash ./scripts/debian/3-build.sh

      - name: Archive server artifact
        uses: actions/upload-artifact@v2
        with:
          name: BeamMP-Server-linux
          path: ./bin/BeamMP-Server

