name: Debian 11 Build

on: [push]

jobs:
  debian-11-build:
    runs-on: ubuntu-latest
    container:
      image: debian:11
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: bash ${{github.workspace}}/scripts/debian/1-install-deps.sh

      - name: Create Build Environment
        run: bash ${{github.workspace}}/scripts/debian/2-configure.sh

      - name: Build Server
        run: bash ${{github.workspace}}/scripts/debian/3-build.sh

      - name: Archive server artifact
        uses: actions/upload-artifact@v2
        with:
          name: BeamMP-Server-linux
          path: ${{github.workspace}}/bin/BeamMP-Server

