name: CMake Linux Build

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  linux-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: 'true'

    - name: Install Dependencies
      run: |
          sudo apt-get update
          sudo apt-get install -y libz-dev rapidjson-dev liblua5.3 libasio-dev

    - name: Cache Boost 1.75.0
      id: cache-boost
      uses: actions/cache@v2
      with:
          path: boost_1_75_0
          key: ${{ runner.os }}-boost

    - name: Install Boost 1.75.0
      if: steps.cache-boost.outputs.cache-hit != 'true'
      run: |
          wget https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.gz
          tar xzf boost_1_75_0.tar.gz
          pushd boost_1_75_0
          ./bootstrap.sh
          ./b2 --build-dir=/tmp/build-boost toolset=gcc --with-system --with-thread
          popd
          rm -f boost_1_75_0.tar.gz

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build-linux

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build-linux
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=g++-10 -DCMAKE_CXX_FLAGS="-L${{github.workspace}}/boost_1_75_0/stage/lib -I${{github.workspace}}/boost_1_75_0"

    - name: Build
      working-directory: ${{github.workspace}}/build-linux
      shell: bash
      run: cmake --build . --config $BUILD_TYPE

